export default [
  {
    name: 'Hambúrguer',
    description: 'Esta é uma descrição de Sanduíches'.toUpperCase(),
    products: [
      {
        name: '',
        description: '',
        items: [
          {
            name: 'BABY BACON',
            id: 0,
            isActive: true,
            image: './static/img/Baby_bacon_site_800x800_acf_cropped.jpg',
            description: 'O mais novo sanduíche da casa! Feito com muito amor e servido em um pão fresquinho com 80g de carne de blend homemade, queijo prato derretido e generosas fatias de bacon defumado à lenha. Ideal para quem está com pouco apetite mas quer se deliciar com um autêntico burguer Bacon Paradise ou para turmas, que podem pedir uma porção com até 10 unidades.',
            value: 8,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'PORQUER',
            id: 1,
            isActive: true,
            image: './static/img/porquer_bacon_paradise1_800x800_acf_cropped.jpg',
            description: 'Pegue suas fichas e dê all-in neste burger! Pão, hambúrguer, queijo prato com pimenta calabresa, salada americana de repolhos, alface e bacon.',
            value: 10,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'HIPSTER PIGGY',
            id: 2,
            isActive: true,
            image: './static/img/hipster_bacon_paradise2_800x800_acf_cropped.jpg',
            description: 'Achou os outros hambúrgueres muito mainstream? Pão, hambúrguer, alho poró e cogumelo fresco salteado na manteiga de garrafa, picles, rúcula, queijo e bacon.',
            value: 12,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'BURLESCO',
            id: 3,
            isActive: true,
            image: './static/img/burlesco_bacon_paradise1_800x800_acf_cropped.jpg',
            description: 'O mais pedido! Pão australiano, hambúrguer, queijo cheddar, bacon frito no açúcar mascavo, pimenta jalapeño, alface e dois deliciosos anéis de cebola.',
            value: 13,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'EAT SWEET',
            id: 4,
            isActive: true,
            image: './static/img/eat_sweet_bacon_paradise2_800x800_acf_cropped.jpg',
            description: 'Pão, hambúrguer, queijo gorgonzola, cebola caramelizada com aquele toque agridoce, alface roxa e bacon. Adoça o coração mais ogro!',
            value: 14,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'TRADICIONAL',
            id: 5,
            isActive: true,
            image: './static/img/tradicional_bacon_paradise1_800x800_acf_cropped.jpg',
            description: 'Pão, hambúrguer, anéis de cebola roxa, alface americana, rodela de tomate e bacon. O queijo é você quem escolhe: prato, cheddar ou gorgonzola.',
            value: 15,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
        ],
      },
    ],
  }, {
    name: 'Bebidas',
    description: '',
    products: [
      {
        name: '',
        description: '',
        items: [
          {
            name: 'CAIP DE MORANGO COM TABASCO',
            id: 6,
            isActive: true,
            image: './static/img/caip_morango_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Delicioso drink picante feito com morango e pimenta tabasco.',
            value: 6,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 3,
          },
          {
            name: 'CAIP UVA COM HORTELÃ',
            id: 7,
            isActive: true,
            image: './static/img/caip_uva_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Uva e hortelã combinados em um drink refrescante',
            value: 6,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'CAIP DE LIMÃO',
            id: 8,
            isActive: true,
            image: './static/img/caip_limao_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'A tradicional! Delícia!',
            value: 6,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'CAIP SICILIANA',
            id: 9,
            isActive: true,
            image: './static/img/caip_siciliana_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Limão Siciliano, Manjericão e Tomate Cereja',
            value: 5,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'SMOKE ON THE WATER',
            id: 10,
            isActive: true,
            image: './static/img/chopp_smoke_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Smoked Ale produzida com malte defumado o que confere aroma e paladar característicos. Grad. Alc.: 6,7% Amargor: 25 IBU Sugestões de Harmonização: Burlesco e Heart Attack.',
            value: 8,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'SCHWEPPES CITRUS',
            id: 11,
            isActive: true,
            image: './static/img/schweppes_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'SCHWEPPES CITRUS',
            value: 5,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 0,
          },
          {
            name: 'CHÁ GELADO LIMÃO',
            id: 12,
            isActive: true,
            image: './static/img/ch-_gelado_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'CHÁ GELADO LIMÃO',
            value: 6,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'REFRIGERANTE LATA',
            id: 13,
            isActive: true,
            image: './static/img/refigerante_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'REFRIGERANTE LATA (350ML)',
            value: 4,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 0,
          },
          {
            name: 'BRAHMA (600ml)',
            id: 14,
            isActive: true,
            image: './static/img/bhrama_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'A LOIRA É A MELHOR COMPANHIA PARA O BACON. AQUI PODE BOTECAR DE ACORDO',
            value: 7,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
        ],
      },
    ],
  }, {
    name: 'Petiscos',
    description: '',
    products: [
      {
        name: '',
        description: '',
        items: [
          {
            name: 'NACHO FRIES',
            id: 15,
            isActive: true,
            image: './static/img/nacho_fries_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Receita clássica do Kentucky. Batatas fritas palito cobertas de chili de carne, tomate e cebola picados, cubinhos de pimenta Jalapeño. E o bacon?? Vem lindo, por cima de tudo. Acompanha molho Ranch e molho Barbecue caseiro.',
            value: 12,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'CHICKEN WINGS',
            id: 16,
            isActive: true,
            image: './static/img/chiken_wings_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Meio da asa de frango frita com manteiga apimentada. Suave. Ardente. Fumegante. Você decide o nível da pimenta. Acompanha molho de Gorgonzola com farofa de BACON!',
            value: 12,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'BACON WRAPPED ONION RINGS',
            id: 17,
            isActive: true,
            image: './static/img/bacon_wrapped_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: '9 anéis de cebola empanados e fritos, envoltos em bacon. Baba não! Pede um logo! Acompanha molho Ranch e molho Barbecue caseiro.',
            value: 13,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'BACON HARUMAKI',
            id: 18,
            isActive: true,
            image: './static/img/harumaki_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Os rolinhos primavera, na versão paraíso. Massa crocante recheada de queijo cheddar, bacon e cubinhos de pimenta Jalapeño. Acompanha molho Barbecue caseiro.',
            value: 11,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'HEART ATTACK',
            id: 19,
            isActive: true,
            image: './static/img/heart_attack_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Prepare o seu coração porque este é matador! Torresmo de barriga frito inteiro, escoltado por tiras de bacon fritas. Acompanha geléia de abacaxi com cachaça.',
            value: 11,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'ONION RINGS',
            id: 20,
            isActive: true,
            image: './static/img/onion_rings_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Anéis de cebola fritos. O verdadeiro Senhor dos Anéis! Delícia vegetariana. Porque este paraíso é para todos. Acompanha molho Ranch e molho Barbecue caseiro.',
            value: 8,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'FRITAS',
            id: 21,
            isActive: true,
            image: './static/img/bacon-batata_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'A nossa velha amiga porção de batatas fritas palito, cobertas de queijo e de tiras de bacon fritas pedindo para serem devoradas. Acompanha molho Barbecue caseiro.',
            value: 11,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
        ],
      },
    ],
  }, {
    name: 'Sobremesas',
    description: '',
    products: [
      {
        name: '',
        description: '',
        items: [
          {
            name: 'MILKSHAKE',
            id: 22,
            isActive: true,
            image: './static/img/milk_shake_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Shake Shake Shake! PRA ACOMPANHAROU PRA FINALIZAR. Sabores: Banana, Ovomaltine e Oreo.',
            value: 8,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
          {
            name: 'NUTELLA EXPLOSION',
            id: 23,
            isActive: true,
            image: './static/img/nutella_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Brownie homemade de chocolate ao leite e chocolate branco, deitado em berço esplêndido de chocolate derretido com castanha, coberto com sorvete de creme e Nutella, coroado por uma tirinha de bacon.',
            value: 9,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 5,
          },
          {
            name: 'WAFFLE',
            id: 24,
            isActive: true,
            image: './static/img/waffle_bacon_paradise_site_800x800_acf_cropped.jpg',
            description: 'Waffle, coberto de rodelas de Banana, Maple Syrup (xarope de bordo), duas bolas de sorvete de creme, calda de caramelo e o toque de mestre: farofa de bacon por cima de tudo!',
            value: 8,
            amount: 1,
            heart: false,
            amountUnit: '',
            selected: 0,
            rated: 4,
          },
        ],
      },
    ],
  },
];
