export default [
  {
    name: 'Hambúrguer',
    description: 'Esta é uma descrição de Sanduíches'.toUpperCase(),
    products: [
      {
        name: 'Frios',
        description: 'Todos servidos com salada',
        items: [
          {
            name: 'Pepin',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 5,
          },
          {
            name: 'Pepino a',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 3,
          },
        ],
      },
      {
        name: 'Quente',
        description: 'Todos servidos com salada',
        items: [
          {
            name: 'Pepino',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 3,
          },
          {
            name: 'Pepino',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 3,
          },
        ],
      },
    ],
  }, {
    name: 'Sanduíches',
    description: 'Esta é uma descrição de Sanduíches'.toUpperCase(),
    products: [
      {
        name: 'Frios',
        description: 'Todos servidos com salada',
        items: [
          {
            name: 'Pepino',
            id: 12,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 2,
          },
          {
            name: 'Pepino',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 3,
          },
        ],
      },
      {
        name: 'Quente',
        description: 'Todos servidos com salada',
        items: [
          {
            name: 'Pepino',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 3,
          },
          {
            name: 'Pepino',
            id: 0,
            isActive: true,
            image: './static/img/background.jpg',
            description: 'pão de forma, pepino japonês, peito de peru e cream cheese',
            value: 8,
            amount: 1,
            amountUnit: 'Sanduíche',
            selected: 0,
            rated: 3,
          },
        ],
      },
    ],
  },
];
